import Section from "../Section";
import AboutBgr from "../AboutBgr";
import RunningString from "../RunningString";
import CrossIcon from "../../assets/icons/cross.svg?react";
import * as s from "./About.styled";

const About = () => {
  return (
    <Section anchorId="about" title="About">
      <AboutBgr>
        <s.DescrWrap>
          <s.SubTitle>
            A Story That Started With
            <s.Span> One Simple{"\n"}Ape</s.Span>
          </s.SubTitle>
          <s.Description>
            Who Got{"\n"}Fed Up With Boring And Hypocritic Commonplace This Is
            How The Idea Of Escaping And Dynamic Journey On The{"\n"}Yacht
          </s.Description>
        </s.DescrWrap>

        <s.TextWrap>
          <s.IconWrap>
            <CrossIcon />
          </s.IconWrap>
          <s.AboutText>
            Each Artwork In The Collection Tells A Story Of One Journey. Arts
            Are Randomly Generated By Users
          </s.AboutText>
        </s.TextWrap>
      </AboutBgr>
      <RunningString />
    </Section>
  );
};

export default About;
